import { ContextAPIProvider } from "@/component/context/ContextAPI";
import "./globals.css";
import { Inter } from "next/font/google";
import ProtectedRout from "@/component/protectedRout/ProtectedRout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextAPIProvider>
          <ProtectedRout />
          {children}
        </ContextAPIProvider>
      </body>
    </html>
  );
}
